### ISSUE TITLE
Feature: Ignore certain types of walls

### ISSUE THREAD

**Issue by Keodant** [SebaSOFT/walls-have-ears#12]
First of all, thank you for this great module

It would be good to have an option to ignore certain types of walls in the module config.

**Comment by SebaSOFT** [comment]
Thanks a lot for using it!

I created a set of tests on the README.md you can see to achieve the result you may want. Bear in mind that this interacts with Sound Restriction, Sound easing and Sound Darkness Ranges, so What you want to do may already be achievable.

This can certainly appear in the future as a "muffling multiplier" setting for each wall. Where 0 is "do not muffle" and 1...4 is the amount of muffling contribution.

**Comment by Keodant** [comment]
Thank you Seba, i'll do that.
