### ISSUE TITLE
[Feature Request] Mark all selected walls sound restriction to none

### ISSUE THREAD

**Issue by NdranC** [SebaSOFT/walls-have-ears#26]
Now that I understand the mod better. I can see how it could be annoying after setting a scene to have to manually click on all the walls making sure the sound settings are correctly set to none. If I try to do this by selecting all walls then all the selected walls will copy all settings to each other instead of just the sound one.

I'm sure this could be done with a macro that could be included with the mod and/or a simple UI button in the wall section to "make all new walls with no sound restrictions".

**Comment by SebaSOFT** [comment]
I will dig into this, but is certainly a dangerous button to press, you can use "limited" and "normal" sound restriction to build complex scenarios and shape the sound, so is not always wanted to remove sound restriction on all scene walls.

**Comment by MoonBrew** [comment]
You can use tagger to tag walls that you care about and then use macros to select walls by tags and then apply any setting you want.

**Comment by Grandsome** [comment]
There's a module called mass edit can that can do this.

**Comment by SebaSOFT** [comment]
Thanks for all the suggestions. It looks like I would be stepping into other mod's features which are richer than what I could/should provide. I will close this with my congrats to the repliers and how they made this mod their own.
