### ISSUE TITLE
Popping noise when moving token

### ISSUE THREAD

**Issue by TehSl0th** [SebaSOFT/walls-have-ears#28]
Hello, I have been experimenting with this module for a little while and noticed that whenever a token is moved, a pop noise happens.
This happens when one moves their own token and when someone else moves their token. I checked out one of your videos on YouTube if this was a user issue and not a module issue and heard the same popping noises there when you moved the token. 
Is there a way to get rid of this noise or is it a side effect of updating the lowpass filter on the move?
Otherwise, this is a solid sound enhancement.

Link to video: https://youtu.be/pT5mhNLVPlQ

**Comment by SebaSOFT** [comment]
Try this again and open a new ticket if your are experiencing the same effect. Now the plugin uses a level cache to avoid changing the filter if its not needed. Filters are still being changed and that perhaps is the popping sound, but it should be greatly rectified.
