### ISSUE TITLE
Too many tokens?

### ISSUE THREAD

**Issue by NukeMaster0** [SebaSOFT/walls-have-ears#3]
![image](https://user-images.githubusercontent.com/68701755/104265352-60ef8880-545b-11eb-9fa2-9c7b82531ed6.png)
I keep getting this error whenever I select more than 3 tokens at once, not really an issue but it is annoying to see it every 5 seconds, what do I do? I tested this with and without the module on a new world and got the same issue.

**Comment by SebaSOFT** [comment]
This is not related to Walls Have Ears, so I would submit the support request on the official FoundryVTT Discord server
