### ISSUE TITLE
Sound plays without muffle when token is moved

### ISSUE THREAD

**Issue by Jordan-stobbs** [SebaSOFT/walls-have-ears#4]
Had an issue with a sound behind a door as a GM, the music would play at full volume once the character was moved (had volume easing on which could have affected things?).

**Comment by SebaSOFT** [comment]
This is related to a sound issue provoked by sound occlusion inner workings, I will keep this in mind but I need the 0.8.x audio overhaul done, first.

**Comment by SebaSOFT** [comment]
This is working fine on FoundrVTT 0.8.6
